stages:
  - test
  - cleanup
  - tweet
  - deploy
  - upload

test_job:
  stage: test
  script:
    - ci/php_build
    - ci/php_test

cleanup:
  stage: cleanup
  script:
    - ci/php_cleanup
  when: always

tweet_succeed_job:
  variables:
    PASSED: "true"
  stage: tweet
  only:
    - tags
    - triggers
    - master
  script:
    - ci/php_tweet

tweet_failed_job:
  variables:
    PASSED: "false"
  stage: tweet
  only:
    - tags
    - triggers
    - master
  script:
    - ci/php_tweet
  when: on_failure

deploy_job:
  stage: deploy
  only:
    - tags
    - triggers
    - master
  script:
    - ci/php_deploy


upload_job_default:
  stage: upload
  only:
    - master
    - triggers
  script:
    - ci/php_upload_default

upload_job_tag:
  stage: upload
  only:
    - tags
  script:
    - ci/php_upload_tag
