stages:
  - test
  - cleanup
  - tweet
  - deploy

test_job:
  stage: test
  script:
    - ci/php_build
    - ci/php_test

cleanup:
  stage: cleanup
  script:
    - ci/php_cleanup
  when: always

tweet_succeed_job:
  variables:
    PASSED: "true"
  stage: tweet
  only:
    - tags
    - triggers
    - master
  script:
    - ci/php_tweet

tweet_failed_job:
  variables:
    PASSED: "false"
  stage: tweet
  only:
    - tags
    - triggers
    - master
  script:
    - ci/php_tweet
  when: on_failure

deploy_job:
  stage: deploy
  only:
    - tags
    - triggers
    - master
  script:
    - ci/php_upload
    - ci/php_deploy
